import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(dirname(packageRoot));

const sourcePath = join(packageRoot, "src/index.ts");
const generatorPath = join(packageRoot, "scripts/generate-mobile-contract.mjs");
const appKotlinPath = join(
  repoRoot,
  "apps/mobile/shared/src/commonMain/kotlin/generated/Contract.kt",
);
const appSwiftPath = join(repoRoot, "apps/mobile/iosApp/SmrtStarter/MobileContract.swift");

describe("mobile contract", () => {
  it("has a versioned contract", async () => {
    const source = await readFile(sourcePath, "utf8");
    assert.match(source, /mobileContractVersion = "\d{4}-\d{2}-\d{2}\.v\d+"/);
    assert.match(source, /interface MobileAuthStartRequest/);
    assert.match(source, /interface MobileAuthSession/);
    assert.match(source, /interface MobileSessionBootstrap/);
    assert.match(source, /type MobileDeviceCaptureSurface = "camera" \| "microphone"/);
    assert.match(source, /interface MobileDeviceCapabilities/);
    assert.match(source, /checkedAtEpochMillis\?: number/);
  });

  it("generates Kotlin into the mobile app source tree", async () => {
    const generator = await readFile(generatorPath, "utf8");
    assert.match(
      generator,
      /apps\/mobile\/shared\/src\/commonMain\/kotlin\/generated\/Contract\.kt/,
    );
    assert.match(generator, /apps\/mobile\/iosApp\/SmrtStarter\/MobileContract\.swift/);
    assert.match(generator, /contractVersion/);
    assert.match(generator, /checkedAtEpochMillis: Long\?/);
    assert.match(generator, /checkedAtEpochMillis: Int64\?/);
  });

  it("keeps the committed app contracts synced with TypeScript models", async () => {
    const [source, appKotlin, appSwift] = await Promise.all([
      readFile(sourcePath, "utf8"),
      readFile(appKotlinPath, "utf8"),
      readFile(appSwiftPath, "utf8"),
    ]);

    const contractVersion = source.match(/mobileContractVersion = "([^"]+)"/)?.[1];
    assert.ok(contractVersion);
    assert.match(appKotlin, /Generated by packages\/mobile-contract/);
    assert.match(appSwift, /Generated by packages\/mobile-contract/);
    assert.ok(appKotlin.includes(`MobileContractVersion = "${contractVersion}"`));
    assert.ok(appSwift.includes(`MobileContractVersion = "${contractVersion}"`));

    const interfaceNames = [...source.matchAll(/export interface (Mobile[A-Za-z0-9]+)/g)].map(
      (match) => match[1],
    );
    assert.ok(interfaceNames.length > 0);
    for (const name of interfaceNames) {
      assert.match(appKotlin, new RegExp(`data class ${name}\\b`));
      assert.match(appSwift, new RegExp(`struct ${name}\\b`));
    }
  });
});
