/**
 * Auto-generated TypeScript declarations for SMRT virtual modules
 * Generated from discovered @smrt() decorated classes
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically regenerated when SMRT objects change
 */

// Manifest module - Contains discovered SMRT objects metadata
declare module '@happyvertical/smrt-virt-manifest' {
  export interface SmrtObjectField {
    type: string;
    required?: boolean;
    default?: any;
  }

  export interface SmrtObjectMethod {
    name: string;
    parameters: Array<{
      name: string;
      type: string;
      required?: boolean;
    }>;
    returnType: string;
    isAsync: boolean;
  }

  export interface SmrtObjectDefinition {
    className: string;
    collection: string;
    fields: Record<string, SmrtObjectField>;
    methods: Record<string, SmrtObjectMethod>;
    decoratorConfig: any;
  }

  export interface SmrtManifest {
    version: string;
    timestamp: number;
    objects: Record<string, SmrtObjectDefinition>;
  }

  export const manifest: SmrtManifest;
}

// Routes module - Auto-generated REST route setup
declare module '@happyvertical/smrt-virt-routes' {
  export interface RouteApp {
    get(path: string, handler: (req: any, res: any) => void): void;
    post(path: string, handler: (req: any, res: any) => void): void;
    put(path: string, handler: (req: any, res: any) => void): void;
    delete(path: string, handler: (req: any, res: any) => void): void;
  }

  export interface RouteOptions {
    basePath?: string;
    [key: string]: any;
  }

  export function setupRoutes(app: RouteApp, options?: RouteOptions): void;
  export default setupRoutes;
}

// Client module - Auto-generated API client
// Wire-shape policy (#1797): the server returns BARE JSON — a bare array for
// list/search, a bare object for get/create/update — with snake_case field
// names (created_at, updated_at). These declarations match that shape (no
// envelope, no camelCase). Fetchers reject on non-2xx with a SmrtClientError
// (#1796). Shared CRUD wire types stay aligned with the prebuild declaration
// path; Vite-only custom action declarations are layered onto them below.
declare module '@happyvertical/smrt-virt-client' {
  /** Structured custom-action failure nested under an API error body's `error` key. */
  export interface SmrtClientFailure {
    ok: false;
    code: string;
    message: string;
    status?: number;
  }

  /** Shape of a JSON error body carried by a rejected request (SmrtClientError.body). */
  export interface ApiError {
    error?: string | SmrtClientFailure;
    message?: string;
  }

  /** Typed error thrown by every fetcher on a non-2xx response (#1796). */
  export interface SmrtClientError extends Error {
    name: 'SmrtClientError';
    status: number;
    /** Machine-readable code from a structured custom-action failure, when present. */
    code?: string;
    body?: ApiError | string;
  }

  export interface CrudOperations<T = any> {
    list(params?: Record<string, any>): Promise<T[]>;
    get(id: string): Promise<T>;
    create(data: Partial<T>): Promise<T>;
    update(id: string, data: Partial<T>): Promise<T>;
    delete(id: string): Promise<boolean>;
    search(query: string): Promise<T[]>;
  }

  export interface ApiClient {
    "starterappsettings": Pick<CrudOperations<StarterAppSettingData>, "list" | "get" | "create" | "update">;
  }

  export function createClient(basePath?: string): ApiClient;
  export default createClient;
}

// MCP module - Auto-generated Model Context Protocol tools
declare module '@happyvertical/smrt-virt-mcp' {
  import type { SmrtMCPServer, MCPServerOptions } from '@happyvertical/smrt-core/runtime';

  export interface McpTool {
    name: string;
    description: string;
    inputSchema: {
      type: string;
      properties: Record<string, any>;
      required?: string[];
    };
  }

  export const tools: McpTool[];
  export function createMCPServer(options?: MCPServerOptions): SmrtMCPServer;
  export default createMCPServer;
}

// Types module - Auto-generated TypeScript interfaces
declare module '@happyvertical/smrt-virt-types' {
  export const types: string;

  // Auto-generated interfaces for discovered SMRT objects
  export interface StarterAppSettingData {
    id?: string;
    key: string;
    value: string;
    updatedByUserId?: string;
    metadata?: any;
    created_at?: string;
    updated_at?: string;
  }

  export interface StarterInvitationData {
    id?: string;
    tokenHash: string;
    email?: string;
    type: string;
    purpose: string;
    status: string;
    invitedByUserId?: string;
    targetTenantId?: string;
    roleId?: string;
    maxUses: number;
    useCount: number;
    expiresAt: string;
    acceptedAt?: string;
    acceptedByUserId?: string;
    metadata?: any;
    created_at?: string;
    updated_at?: string;
  }

  export default types;
}

// Web module - Typed collection definitions for the browser client data
// runtime (@happyvertical/smrt-web, #1761)
declare module '@happyvertical/smrt-virt-web' {
  export type SmrtWebFieldType =
    | 'text'
    | 'decimal'
    | 'boolean'
    | 'integer'
    | 'datetime'
    | 'json'
    | 'foreignKey'
    | 'crossPackageRef';

  /** Static `@field({ ui })` hints (#2046) — the field-policy rail seed. */
  export interface SmrtWebFieldUIHints {
    basic?: boolean;
    group?: string;
    order?: number;
    locked?: boolean;
  }

  export interface SmrtWebFieldDefinition {
    type: SmrtWebFieldType;
    required?: boolean;
    nullable?: boolean;
    default?: unknown;
    /** Developer-authored `@field({ description })` (#2046) — end-user help seed. */
    description?: string;
    /** Static `@field({ ui })` hints (#2046). */
    ui?: SmrtWebFieldUIHints;
  }

  export type SmrtWebRelationshipKind =
    | 'foreignKey'
    | 'crossPackageRef'
    | 'oneToMany'
    | 'manyToMany';

  /**
   * A manifest-derived edge to a sibling REST collection. Mutating this
   * collection invalidates the caches of the collections named by these edges
   * (#1761 relationship-derived invalidation).
   */
  export interface SmrtWebRelationship {
    field: string;
    kind: SmrtWebRelationshipKind;
    relatedCollection: string;
  }

  /** A WebMCP/MCP tool descriptor for one collection action (#1812). */
  export interface WebToolDescriptor {
    action: string;
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;
    readOnly: boolean;
  }

  export interface SmrtWebCollectionDefinition<TData = Record<string, unknown>> {
    name: string;
    /** Canonical qualified model identity (`@package/name:ClassName`) for policy APIs. */
    objectRef: string;
    className: string;
    endpoint: string;
    idField: string;
    actions: string[];
    fields: Record<string, SmrtWebFieldDefinition>;
    /** Manifest-derived relationship edges to sibling REST collections. */
    relationships: SmrtWebRelationship[];
    /** WebMCP/MCP tool descriptors for the exposed actions (#1812). */
    toolDescriptors: WebToolDescriptor[];
    /** Phantom row-type carrier for inference — never present at runtime. */
    _row?: TData;
  }

  export interface SmrtWebCollectionDefinitions {
    "starterappsettings": SmrtWebCollectionDefinition<import('@happyvertical/smrt-virt-types').StarterAppSettingData>;
  }

  export const collectionDefinitions: SmrtWebCollectionDefinitions;
  export function getCollectionDefinition<
    K extends keyof SmrtWebCollectionDefinitions,
  >(name: K): SmrtWebCollectionDefinitions[K];
  /**
   * Build-time web-collection shape digest (#1764). A deterministic,
   * replica-stable hash of the emitted collection definitions; a change means
   * old persisted client rows may mis-hydrate. Consumers fold it into the
   * durable persistence namespace and the version-awareness updateAvailable
   * contract signal. One of the co-managed emission sites that must not drift —
   * the runtime value, this ambient d.ts, the physical @smrt/web d.ts, and the
   * hand-written @happyvertical/smrt-web type mirror.
   */
  export const manifestHash: string;
  export default collectionDefinitions;
}

// CLI module - Auto-generated command-line interface
declare module '@happyvertical/smrt-virt-cli' {
  export interface CLIConfig {
    name?: string;
    version?: string;
    description?: string;
    prompt?: boolean;
    colors?: boolean;
  }

  export interface CLIContext {
    db?: any;
    ai?: any;
    user?: {
      id: string;
      roles?: string[];
    };
  }

  export interface CLICommandMap {
    [objectName: string]: {
      collection: string;
      commands: string[];
    };
  }

  export const cliCommands: CLICommandMap;

  export function setupCLI(config?: CLIConfig, context?: CLIContext): {
    run: (argv: string[]) => Promise<void>;
    generator: any;
  };

  export function getCLIHandler(config?: CLIConfig, context?: CLIContext): (argv: string[]) => Promise<void>;

  export default setupCLI;
}