// Generated by packages/mobile-contract/scripts/generate-mobile-contract.mjs.
// Do not edit manually.
import Foundation

let MobileContractVersion = "2026-06-08.v4"

struct MobileTenantSummary {
  let id: String
  let name: String
  let slug: String
  let planName: String
  let subscriptionStatus: String
}

struct MobileTenantOption {
  let id: String
  let name: String
  let slug: String
  let roleSlug: String
  let roleLabel: String
}

struct MobileUsageThreshold {
  let metricKey: String
  let label: String
  let used: Double
  let limit: Double
  let action: String
  let state: String?
  let allowed: Bool?
  let remaining: Double?
}

struct MobileDashboardPayload {
  let tenant: MobileTenantSummary
  let thresholds: [MobileUsageThreshold]
  let enabledFeatures: [String]
  let language: String
}

struct MobileAuthProviderSummary {
  let id: String
  let label: String
  let type: String
  let supportsPkce: Bool
}

struct MobileAuthStartRequest {
  let providerId: String?
  let redirectUri: String
  let scopes: [String]
  let state: String?
  let loginHint: String?
}

struct MobileAuthStartResponse {
  let providerId: String
  let authorizationUrl: String
  let state: String
  let codeVerifier: String?
  let nonce: String?
  let redirectUri: String
}

struct MobileAuthCompleteRequest {
  let providerId: String?
  let code: String
  let state: String?
  let codeVerifier: String?
  let redirectUri: String
}

struct MobileUserSummary {
  let id: String
  let email: String
  let label: String
}

struct MobileAuthSession {
  let accessToken: String
  let tokenType: String
  let expiresAt: String
  let user: MobileUserSummary
  let activeTenant: MobileTenantOption
  let tenants: [MobileTenantOption]
}

struct MobileSessionBootstrap {
  let user: MobileUserSummary
  let activeTenant: MobileTenantOption
  let tenants: [MobileTenantOption]
  let dashboard: MobileDashboardPayload
}

struct MobileDevicePermissionState {
  let status: String
  let canRequest: Bool
  let reason: String?
}

struct MobileDeviceCapability {
  let surface: String
  let label: String
  let supported: Bool
  let permission: MobileDevicePermissionState
  let preferredInput: String
}

struct MobileDeviceCapabilities {
  let camera: MobileDeviceCapability
  let microphone: MobileDeviceCapability
  let checkedAtEpochMillis: Int64?
}
